// RunLocal Model Database
// Last updated: 2026-04-08. Add new models here.
// Each model entry contains sizing info, performance estimates, and metadata.
// Keep this file separate from UI code for easy updates.

export const MODEL_DATABASE = [
  // --- Tier 1: Small Models (< 5GB) ---
  {
    id: 'phi3-mini',
    name: 'Phi-3 Mini',
    family: 'Microsoft Phi',
    parameterCount: '3.8B',
    quantization: 'Q4_K_M',
    fileSizeGB: 2.4,
    vramRequiredGB: 3.2,
    ramRequiredGB: 4.0,
    contextLength: 4096,
    kvCacheGB: 0.5,
    bestFor: ['Chat', 'Summarization'],
    expectedTPS: { high: 50, mid: 30, low: 8 },
    ollamaCommand: 'ollama pull phi3:mini',
    runCommand: 'ollama run phi3:mini',
    ollamaUrl: 'https://ollama.com/library/phi3',
    whyThisModel: 'Smallest model that still feels smart. Great for quick tasks.',
    releaseDate: '2024-04',
  },
  {
    id: 'llama3.2-3b',
    name: 'Llama 3.2 3B',
    family: 'Meta Llama',
    parameterCount: '3B',
    quantization: 'Q4_K_M',
    fileSizeGB: 2.0,
    vramRequiredGB: 2.8,
    ramRequiredGB: 3.5,
    contextLength: 8192,
    kvCacheGB: 0.6,
    bestFor: ['Chat', 'Summarization'],
    expectedTPS: { high: 60, mid: 35, low: 10 },
    ollamaCommand: 'ollama pull llama3.2:3b',
    runCommand: 'ollama run llama3.2:3b',
    ollamaUrl: 'https://ollama.com/library/llama3.2',
    whyThisModel: "Meta's smallest Llama. Fast, lightweight, surprisingly capable.",
    releaseDate: '2024-09',
  },
  {
    id: 'gemma2-2b',
    name: 'Gemma 2 2B',
    family: 'Google Gemma',
    parameterCount: '2B',
    quantization: 'Q4_K_M',
    fileSizeGB: 1.6,
    vramRequiredGB: 2.2,
    ramRequiredGB: 3.0,
    contextLength: 8192,
    kvCacheGB: 0.4,
    bestFor: ['Chat', 'Summarization'],
    expectedTPS: { high: 70, mid: 40, low: 12 },
    ollamaCommand: 'ollama pull gemma2:2b',
    runCommand: 'ollama run gemma2:2b',
    ollamaUrl: 'https://ollama.com/library/gemma2',
    whyThisModel: "Google's tiny model. Fastest option for low-end hardware.",
    releaseDate: '2024-06',
  },

  // --- Tier 2: Medium Models (5-10GB) ---
  {
    id: 'llama3.1-8b',
    name: 'Llama 3.1 8B',
    family: 'Meta Llama',
    parameterCount: '8B',
    quantization: 'Q4_K_M',
    fileSizeGB: 4.9,
    vramRequiredGB: 6.0,
    ramRequiredGB: 8.0,
    contextLength: 8192,
    kvCacheGB: 1.0,
    bestFor: ['Chat', 'Coding', 'Creative'],
    expectedTPS: { high: 35, mid: 18, low: 5 },
    ollamaCommand: 'ollama pull llama3.1:8b',
    runCommand: 'ollama run llama3.1:8b',
    ollamaUrl: 'https://ollama.com/library/llama3.1',
    whyThisModel: 'The sweet spot. Best all-around model for 8GB VRAM.',
    releaseDate: '2024-07',
  },
  {
    id: 'mistral-7b',
    name: 'Mistral 7B',
    family: 'Mistral AI',
    parameterCount: '7B',
    quantization: 'Q4_K_M',
    fileSizeGB: 4.4,
    vramRequiredGB: 5.5,
    ramRequiredGB: 7.0,
    contextLength: 8192,
    kvCacheGB: 0.8,
    bestFor: ['Chat', 'Coding'],
    expectedTPS: { high: 38, mid: 20, low: 6 },
    ollamaCommand: 'ollama pull mistral:7b',
    runCommand: 'ollama run mistral:7b',
    ollamaUrl: 'https://ollama.com/library/mistral',
    whyThisModel: 'Punches above its weight in reasoning. Strong coder.',
    releaseDate: '2023-12',
  },
  {
    id: 'gemma2-9b',
    name: 'Gemma 2 9B',
    family: 'Google Gemma',
    parameterCount: '9B',
    quantization: 'Q4_K_M',
    fileSizeGB: 5.4,
    vramRequiredGB: 6.5,
    ramRequiredGB: 8.5,
    contextLength: 8192,
    kvCacheGB: 1.0,
    bestFor: ['Chat', 'Summarization', 'Creative'],
    expectedTPS: { high: 30, mid: 16, low: 4 },
    ollamaCommand: 'ollama pull gemma2:9b',
    runCommand: 'ollama run gemma2:9b',
    ollamaUrl: 'https://ollama.com/library/gemma2',
    whyThisModel: "Google's mid-tier. Excellent at following instructions.",
    releaseDate: '2024-06',
  },
  {
    id: 'qwen2.5-7b',
    name: 'Qwen 2.5 7B',
    family: 'Alibaba Qwen',
    parameterCount: '7B',
    quantization: 'Q4_K_M',
    fileSizeGB: 4.7,
    vramRequiredGB: 5.8,
    ramRequiredGB: 7.5,
    contextLength: 32768,
    kvCacheGB: 1.5,
    bestFor: ['Chat', 'Coding', 'Summarization'],
    expectedTPS: { high: 34, mid: 18, low: 5 },
    ollamaCommand: 'ollama pull qwen2.5:7b',
    runCommand: 'ollama run qwen2.5:7b',
    ollamaUrl: 'https://ollama.com/library/qwen2.5',
    whyThisModel: 'Longest context window in this size class. Great for documents.',
    releaseDate: '2024-09',
  },
  {
    id: 'deepseek-coder-6.7b',
    name: 'DeepSeek Coder 6.7B',
    family: 'DeepSeek',
    parameterCount: '6.7B',
    quantization: 'Q4_K_M',
    fileSizeGB: 4.0,
    vramRequiredGB: 5.0,
    ramRequiredGB: 6.5,
    contextLength: 16384,
    kvCacheGB: 1.2,
    bestFor: ['Coding'],
    expectedTPS: { high: 40, mid: 22, low: 6 },
    ollamaCommand: 'ollama pull deepseek-coder:6.7b',
    runCommand: 'ollama run deepseek-coder:6.7b',
    ollamaUrl: 'https://ollama.com/library/deepseek-coder',
    whyThisModel: 'Purpose-built for code. Best coding model in the small tier.',
    releaseDate: '2024-01',
  },
  {
    id: 'phi3-medium',
    name: 'Phi-3 Medium',
    family: 'Microsoft Phi',
    parameterCount: '14B',
    quantization: 'Q4_K_M',
    fileSizeGB: 8.2,
    vramRequiredGB: 9.5,
    ramRequiredGB: 12.0,
    contextLength: 4096,
    kvCacheGB: 1.0,
    bestFor: ['Chat', 'Summarization', 'Creative'],
    expectedTPS: { high: 22, mid: 12, low: 3 },
    ollamaCommand: 'ollama pull phi3:medium',
    runCommand: 'ollama run phi3:medium',
    ollamaUrl: 'https://ollama.com/library/phi3',
    whyThisModel: "Microsoft's mid-range. Great reasoning for its size.",
    releaseDate: '2024-05',
  },

  // --- Tier 3: Large Models (10-20GB) ---
  {
    id: 'qwen2.5-14b',
    name: 'Qwen 2.5 14B',
    family: 'Alibaba Qwen',
    parameterCount: '14B',
    quantization: 'Q4_K_M',
    fileSizeGB: 8.9,
    vramRequiredGB: 10.0,
    ramRequiredGB: 13.0,
    contextLength: 32768,
    kvCacheGB: 2.0,
    bestFor: ['Chat', 'Coding', 'Summarization'],
    expectedTPS: { high: 20, mid: 10, low: 3 },
    ollamaCommand: 'ollama pull qwen2.5:14b',
    runCommand: 'ollama run qwen2.5:14b',
    ollamaUrl: 'https://ollama.com/library/qwen2.5',
    whyThisModel: 'Best 14B model. Massive context window for analysis.',
    releaseDate: '2024-09',
  },
  {
    id: 'deepseek-r1-14b',
    name: 'DeepSeek R1 14B',
    family: 'DeepSeek',
    parameterCount: '14B',
    quantization: 'Q4_K_M',
    fileSizeGB: 9.0,
    vramRequiredGB: 10.5,
    ramRequiredGB: 13.5,
    contextLength: 16384,
    kvCacheGB: 1.8,
    bestFor: ['Chat', 'Coding', 'Summarization'],
    expectedTPS: { high: 20, mid: 10, low: 3 },
    ollamaCommand: 'ollama pull deepseek-r1:14b',
    runCommand: 'ollama run deepseek-r1:14b',
    ollamaUrl: 'https://ollama.com/library/deepseek-r1',
    whyThisModel: 'Reasoning-focused model. Think step-by-step. Strong at math and logic.',
    releaseDate: '2025-01',
  },
  {
    id: 'gemma2-27b',
    name: 'Gemma 2 27B',
    family: 'Google Gemma',
    parameterCount: '27B',
    quantization: 'Q4_K_M',
    fileSizeGB: 16.0,
    vramRequiredGB: 18.0,
    ramRequiredGB: 22.0,
    contextLength: 8192,
    kvCacheGB: 2.0,
    bestFor: ['Chat', 'Summarization', 'Creative'],
    expectedTPS: { high: 16, mid: 7, low: 2 },
    ollamaCommand: 'ollama pull gemma2:27b',
    runCommand: 'ollama run gemma2:27b',
    ollamaUrl: 'https://ollama.com/library/gemma2',
    whyThisModel: "Google's best open model. Strong reasoning and instruction following.",
    releaseDate: '2024-06',
  },
  {
    id: 'qwen2.5-32b',
    name: 'Qwen 2.5 32B',
    family: 'Alibaba Qwen',
    parameterCount: '32B',
    quantization: 'Q4_K_M',
    fileSizeGB: 19.0,
    vramRequiredGB: 21.0,
    ramRequiredGB: 25.0,
    contextLength: 32768,
    kvCacheGB: 3.0,
    bestFor: ['Chat', 'Coding', 'Creative', 'Summarization'],
    expectedTPS: { high: 14, mid: 6, low: 1.5 },
    ollamaCommand: 'ollama pull qwen2.5:32b',
    runCommand: 'ollama run qwen2.5:32b',
    ollamaUrl: 'https://ollama.com/library/qwen2.5',
    whyThisModel: 'Arguably the best open model under 24GB VRAM. Do-it-all.',
    releaseDate: '2024-09',
  },
  {
    id: 'codellama-34b',
    name: 'Code Llama 34B',
    family: 'Meta Llama',
    parameterCount: '34B',
    quantization: 'Q4_K_M',
    fileSizeGB: 20.0,
    vramRequiredGB: 22.0,
    ramRequiredGB: 26.0,
    contextLength: 16384,
    kvCacheGB: 2.5,
    bestFor: ['Coding'],
    expectedTPS: { high: 14, mid: 6, low: 1.5 },
    ollamaCommand: 'ollama pull codellama:34b',
    runCommand: 'ollama run codellama:34b',
    ollamaUrl: 'https://ollama.com/library/codellama',
    whyThisModel: 'The best open-source coding model at this size.',
    releaseDate: '2023-08',
  },
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral 8x7B',
    family: 'Mistral AI',
    parameterCount: '46.7B (MoE)',
    quantization: 'Q4_K_M',
    fileSizeGB: 26.0,
    vramRequiredGB: 28.0,
    ramRequiredGB: 32.0,
    contextLength: 32768,
    kvCacheGB: 3.0,
    bestFor: ['Chat', 'Coding', 'Creative'],
    expectedTPS: { high: 12, mid: 5, low: 1 },
    ollamaCommand: 'ollama pull mixtral:8x7b',
    runCommand: 'ollama run mixtral:8x7b',
    ollamaUrl: 'https://ollama.com/library/mixtral',
    whyThisModel: 'Mixture of Experts — GPT-3.5 class quality. Needs 24GB+ VRAM.',
    releaseDate: '2024-01',
  },

  // --- Tier 4: Flagship Models (20GB+) ---
  {
    id: 'llama3.1-70b',
    name: 'Llama 3.1 70B',
    family: 'Meta Llama',
    parameterCount: '70B',
    quantization: 'Q4_K_M',
    fileSizeGB: 40.0,
    vramRequiredGB: 42.0,
    ramRequiredGB: 48.0,
    contextLength: 8192,
    kvCacheGB: 4.0,
    bestFor: ['Chat', 'Coding', 'Creative', 'Summarization'],
    expectedTPS: { high: 8, mid: 3, low: 0.5 },
    ollamaCommand: 'ollama pull llama3.1:70b',
    runCommand: 'ollama run llama3.1:70b',
    ollamaUrl: 'https://ollama.com/library/llama3.1',
    whyThisModel: 'Frontier-class quality. Needs serious hardware.',
    releaseDate: '2024-07',
  },
];
